---
title: Test KBOY
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kirbyy.james@gmail.com
description: KBOY
baseurl: ''
url: http:localhost
twitter_username: FernandezKboy
github_username: kboygit
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
